DROP DATABASE IF EXISTS `LarssonLibrary`;
CREATE DATABASE `LarssonLibrary`;
USE `LarssonLibrary`;

DROP TABLE IF EXISTS `Author`;
CREATE TABLE `Author` (
	`AuthorID` INT NOT NULL AUTO_INCREMENT,
	`DisplayName` VARCHAR(255) NOT NULL,
	`FirstName` VARCHAR(255) NOT NULL,
	`LastName` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`AuthorID`),
	INDEX `IDX_AUTHOR_FIRSTNAME` (`FirstName`),
	INDEX `IdX_AUTHOR_LASTNAME` (`LastName`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `BookSeries`;
CREATE TABLE `BookSeries` (
	`BookSeriesID` INT NOT NULL AUTO_INCREMENT,
	`Title` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`BookSeriesID`),
	UNIQUE KEY `BOOKSERIES_TITLE` (`Title`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Book`;
CREATE TABLE `Book` (
	`BookID` INT NOT NULL AUTO_INCREMENT,
	`ISBN13` CHAR(13) NOT NULL,
	`AuthorID` INT NOT NULL,
	`BookSeriesID` INT NULL DEFAULT NULL,
	`Title` VARCHAR(255) NOT NULL,
	`Synopsis` TEXT NOT NULL,
	PRIMARY KEY (`BookID`),
	INDEX `IDX_BOOK_ISBN13` (`ISBN13`),
	INDEX `IDX_BOOK_TITLE` (`Title`),
	UNIQUE KEY `BOOK_ISBN13` (`ISBN13`),
	UNIQUE KEY `BOOK_AUTHORID_TITLE` (`AuthorID`, `Title`),
	FOREIGN KEY `FK_BOOK_AUTHORID` (`AuthorID`) REFERENCES `Author` (`AuthorID`),
	FOREIGN KEY `FK_BOOK_BOOKSERIESID` (`BookSeriesID`) REFERENCES `BookSeries` (`BookSeriesID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` (
	`UserID` INT NOT NULL AUTO_INCREMENT,
	`DisplayName` VARCHAR(255) NOT NULL,
	`FirstName` VARCHAR(255) NOT NULL,
	`LastName` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`UserID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Checkout`;
CREATE TABLE `Checkout` (
	`CheckoutID` INT NOT NULL AUTO_INCREMENT,
	`BookID` INT NOT NULL,
	`UserID` INT NOT NULL,
	`OutDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`InDate` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`CheckoutID`),
	FOREIGN KEY `FK_CHECKOUT_BOOKID` (`BookID`) REFERENCES `Book` (`BookID`),
	FOREIGN KEY `FK_USER_USERID` (`UserID`) REFERENCES `User` (`UserID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
